# Generated by Django 3.2.8 on 2021-10-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('selected', models.BooleanField(default=False)),
                ('origin', models.BooleanField(default=False)),
                ('destination', models.BooleanField(default=False)),
            ],
        ),
    ]
